name: big-auth
version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: big-auth-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_BIG_AUTH}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - big-auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_BIG_AUTH}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  big-auth-network:
    driver: bridge
